[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.108",
    "fastapi[standard]>=0.142.2",
    "numpy>=2.5.3",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
